### ISSUE TITLE
Unknown node type JSXElement

### ISSUE THREAD

**Issue by gsklee** [facebook/esprima#100]
I kept getting this error when using JSCS after upgrading esprima-fb from 12001.1.0-dev-harmony-fb to 13001.1.0-dev-harmony-fb...

```
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: Unknown node type JSXElement.

Unknown node type JSXElement.

Unknown node type JSXElement.

Unknown node type JSXElement.

Unknown node type JSXElement.

Unknown node type JSXElement.

Unknown node type JSXElement.

Unknown node type JSXElement.

Unknown node type JSXElement.

Unknown node type JSXElement.

Unknown node type JSXElement.

Unknown node type JSXElement.

Unknown node type JSXElement.

Unknown node type JSXElement.
```

My app is a typical react app with the standard ES6 syntax found on the react blog, and stays unchanged before/after the upgrade.

**Comment by syranide** [comment]
facebook/react#3264 probably?

**Comment by fkling** [comment]
Seems to be fixed in JSCS now: https://github.com/jscs-dev/node-jscs/issues/1131

**Comment by zpao** [comment]
This isn't on our plate so going to close out.
