### ISSUE TITLE
react/prop-types validation broken using this.props[someVar]

### ISSUE THREAD

**Issue by justin808** [facebook/esprima#113]
This line below fails:

```
if (this.props[propertyName]) {
```

with
```
warning  'propertyName' is missing in props validation  react/prop-types
```

Using:     "esprima-fb": "^15001.1.0-dev-harmony-fb",

**Comment by spicyj** [comment]
Is that an eslint warning? esprima doesn't give warnings like that.

**Comment by zpao** [comment]
I think that's coming from https://github.com/yannickcr/eslint-plugin-react

**Comment by justin808** [comment]
@zpao Thanks I reported it there!
