### ISSUE TITLE
Spread must be the final element of an element list

### ISSUE THREAD

**Issue by raine** [facebook/esprima#117]
I got this error with [`cardinal`](https://github.com/thlorenz/cardinal) which I suppose uses esprima-fb under the hood:

```
Error: Unable to perform highlight.
The code contained syntax errors: Line 101: Spread must be the final element of an element list
```

The line is:

```
101| const partials = mergeTemplateItems(filterMatchingTemplates(...args, Types.PARTIAL));
```

The code compiles as expected with babel though. Am I using the spread operator wrong?

**Comment by spicyj** [comment]
I'm not sure off the top of my head but esprima-fb isn't maintained any more, sorry. We've switched to Babel internally and suggest other people do too since it's much more actively maintained.
