### ISSUE TITLE
Move from XJS prefixes to JSX

### ISSUE THREAD

**Issue by RReverser** [facebook/esprima#83]
Following talk with @sebmarkbage, decided to bring this issue back.

Earlier the only thing I was worried about was that this might break backward compatibility for other AST tools, but now [Espree](https://github.com/eslint/espree) (<=> [ESLint](https://github.com/eslint/eslint)) has already [switched from XJS to JSX prefixes](https://github.com/eslint/eslint/commit/f90d1537a50df224137792f2bd6dcf3e781dfffa#commitcomment-9262570) for internal needs.

In [Acorn-JSX](https://github.com/RReverser/acorn-jsx) (<=> [6to5](https://github.com/6to5/6to5)) I'd like to do the same, but wouldn't want to do that without agreement with primary player (Esprima-FB), as it exposes AST to outer consumers.

**Comment by jeffmo** [comment]
I'd spoken with @nzakas about Espree just going ahead and doing this.

I think it'd be a safe bet -- the only downstream effects that need to come with the change (at least within a reasonable buffer of time) would be updates to the transform code.

Should mostly be just a big search/replace job with some version kung fu I imagine.

**Comment by RReverser** [comment]
Cool! Let's do it.

**Comment by nzakas** [comment]
Yeah, when I transitioned ESLint from esprima-fb to Espree, I literally did a find-replace XJS -> JSX and it worked swimmingly. :)

**Comment by nzakas** [comment]
Hooray!

**Comment by RReverser** [comment]
Yay! :)
