### ISSUE TITLE
Support YieldExpression

### ISSUE THREAD

**Issue by rstacruz** [facebook/esprima#90]
```js
function* fn () {
  yield true;
}
```

I believe this has been implemented in upstream.

**Comment by fkling** [comment]
It is implemented: http://felix-kling.de/esprima_ast_explorer/#/cCx50bzQ9u Am I missing something?

**Comment by rstacruz** [comment]
great, thanks! looks like the version js2coffee 2.0 is using is [not](http://js2.coffee/#try:function%20fn%28%29%20{%0A%20%20yield%20true%3B%0A}) picking it up (the error there is an esprima error).

**Comment by rstacruz** [comment]
oops. got confused. turns out you cant `function fn() { yield true }` without the function being a generator function.

**Comment by fkling** [comment]
That's correct :)
