### ISSUE TITLE
JSX parsing error

### ISSUE THREAD

**Issue by glenjamin** [facebook/esprima#91]
I'm not entirely sure what's causing the issue here:

This fails
```jsx
function play(moves) {
    var game = gamelib.create();
    var player = gamelib.createPlayer();
    return moves.reduce(
        ([[g, p], [x, y]]) => gamelib.play(g, x, y, p),
        [game, player],
        moves
    );
}
```

This doesn't

```js
([[g, p], [x, y]]) => gamelib.play(g, x, y, p),
```

**Comment by fkling** [comment]
Are you getting

> Syntax error: Line 5: Unexpected token =>

?

We fixed this in 0e4014d2e0d4c024c3481acdad7e7a813195527b, but we haven't pushed out a new version yet. cc @jeffmo

**Comment by zpao** [comment]
Well, we tried to push out a version with that :P. Let's get #89 in, merge upstream, then get a new version published so jstransform (and thus react) can get the changes.

**Comment by zpao** [comment]
This seems like it works in v10
