### ISSUE TITLE
Why throw errorTolerant with `import` and `export` ?

### ISSUE THREAD

**Issue by jackfranklin** [facebook/esprima#98]
I have just swapped a project from "regular" esprima to this one in an attempt to get better ES6 support, in particular the modules syntax.

I was just wondering if someone could explain to me (as much out of interest as anything else) why the below code is as is? It seems to me like all the code for parsing imports and exports are in place, and I could find tests for them, but right now the moment an import or export is encountered an error is thrown immediately. Why is this?

```js
  case 'export':
    throwErrorTolerant({}, Messages.IllegalExportDeclaration);
    return parseExportDeclaration();
  case 'import':
    throwErrorTolerant({}, Messages.IllegalImportDeclaration);
    return parseImportDeclaration();
```

Thank you!

Jack

**Comment by zpao** [comment]
I think it's a "looser" parsing mode. This actually landed in the upstream harmony branch and isn't specific to our harmony release (see https://code.google.com/p/esprima/issues/detail?id=619 and https://github.com/jquery/esprima/commit/b1dd29e985b353648a6e0fa8b9f852cd2db228ac). The link to the similar change in Acorn is probably the most informative piece (https://github.com/marijnh/acorn/issues/174).

cc @jeffmo who might have more context. I'm going to close the issue but feel free to keep discussing.
